### ISSUE TITLE
For smartmove protocol, position data from document.txt is odd

### ISSUE THREAD

**Issue by agricolab** [translationalneurosurgery/tool-offspect#1]
@FelixQuirm  Inoticed that the position data from document.txt is odd, i.e. [-45, 178, 220] or similar. That would mean far away from the head. it might actually be the position of the robots end point, and not the position of the coil.  any info on how to derive coil position from robot position?

**Comment by FelixQuirm** [comment]
The offset stems from the headmodel we used, which for some reason was not actually centred in the origin of the coordinate system. By contrasting it with another model created at the origin, I obtained a good approximation for the offset, which should be [0, 255, 0].

**Comment by agricolab** [comment]
Further inspection also suggests that coordinates are scaled by the factor 2, meaning a correct transformation matrix could e.g. be:
```python
tm = np.asanyarray([[.5, 0, 0, 0], [0, .5, 0, -255],[0, 0, .5, 0],[0, 0, 0, 1]])
array([[   0.5,    0. ,    0. ,    0. ],
       [   0. ,    0.5,    0. , -255. ],
       [   0. ,    0. ,    0.5,    0. ],
       [   0. ,    0. ,    0. ,    1. ]])

```
