### ISSUE TITLE
Error with merging when using -f *.hdf5

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#10]
In the documentation - Development - GUI test and development it is described to merge two example files using the command: offspect merge -f *.hdf5 -t merged.hdf5 . For me this results in an error 

![merge](https://user-images.githubusercontent.com/54707165/77299456-c2881000-6cec-11ea-8b04-8e276cb9eb74.PNG)
 

It works when using: offspect merge -f fname1.hdf5 fname2.hdf5 -t merged.hdf5

![merge_solution](https://user-images.githubusercontent.com/54707165/77299841-65d92500-6ced-11ea-9e2e-60ef29c3250a.PNG)

**Comment by agricolab** [comment]
Thanks! Must be how the windows command prompt deals with stars (i.e. *)
