### ISSUE TITLE
Error when converting Matlab TMS-Map data to Cachefile

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#14]
After installing tool-load-tms in environment, I get the following error when trying to convert matlab TMS-data to a Cachefile:

![error_matab3](https://user-images.githubusercontent.com/54707165/77629475-dda38b80-6f49-11ea-8b43-c83df007860d.PNG)

Matlab Command Window:
![error_matlab2](https://user-images.githubusercontent.com/54707165/77629527-f613a600-6f49-11ea-8907-e2535883da64.PNG)

And Matlab Editor:
![error_matlab1](https://user-images.githubusercontent.com/54707165/77629578-09bf0c80-6f4a-11ea-8907-e4e6ca8dddaa.PNG)

**Comment by agricolab** [comment]
Considering all other fields were found, it looks like for this recording there is no `dataSub.date` field.  Can you open the matfile manually and inspect it? Additionally, i catch the exception now, and would you be so kind and test whether https://github.com/translationalneurosurgery/tool-load-tms/commit/8240fad2a4cfa89374e387729f4e00cdc32b8534 fixed the issue

**Comment by BettinaTrunk** [comment]
That's true, there is no field dataSub.date also not in other datasets. For both screenig TMS Map datasets, the date seems to be stored in: obj.dataSub.initials(6:16)

**Comment by BettinaTrunk** [comment]
When running it again with your changes, I get the following error:
![error_matlab4](https://user-images.githubusercontent.com/54707165/77636364-4859c480-6f54-11ea-8ffa-c6043377cf09.PNG)

**Comment by BettinaTrunk** [comment]
... with both screening TMS Map datasets I mean the data from screening 1 (Lukas) and sreening 2 (Bettina)

**Comment by agricolab** [comment]
Thanks, this is the tail of having to deal with the missing date in the obj. Should be fixed with https://github.com/translationalneurosurgery/tool-offspect/commit/b821916391da786a5ba8a2f310201741a5ae33f3 . Can you pull the most recent version and try again?

**Comment by agricolab** [comment]
Fixed by https://github.com/translationalneurosurgery/tool-offspect/commit/05b4946436d397bc8c2e5aafd45179233e8d3687
