### ISSUE TITLE
Feature: Show and edit both comments in the GUI

### ISSUE THREAD

**Issue by agricolab** [translationalneurosurgery/tool-offspect#16]
**Is your feature request related to a problem? Please describe.**
There are two comments field in the MetaData, one is [global_comment](https://github.com/translationalneurosurgery/tool-offspect/blob/develop/tests/mock/cache_template.yml#L11), the other 
the [comment per trace](https://github.com/translationalneurosurgery/tool-offspect/blob/develop/tests/mock/cache_template.yml#L32). Currently, we only show the trace-wise comment in the GUI. 

**Describe the solution you'd like**
Both comments should be editable and visible from the GUI, ideally in separate QTextEdits.

**Describe alternatives you've considered**
An alternative is to allow editing the global_comment only from a Menu in the GUI or with a CLI command. The first one has its merit, as it strengthens the difference of global_comments versus trace_wise_comments. The latter would be quite cumbersome.

**Additional context**
It should be noted that global_comments are per orginal file within the (merged) CacheFile. Currently, there is no way to annotate a full CacheFile implemented (e.g. for logging manipulations or history).

**Comment by ethanrich** [comment]
If a main menu is needed, it could include the global comment when the file is uploaded:
![Capture](https://user-images.githubusercontent.com/48725637/78015680-0791ef00-734a-11ea-8abe-a19b0ca0576a.PNG)

Alternatively, the GUI comment box is currently reading global_comment. A tab menu can separate global from trace easily.

**Comment by agricolab** [comment]
I like the tab approach, but is there a reason why you want one hidden? Why not show both at the same time?
It is a different topic, but a main menu adds states and complexity, so i'd shy away unless necessary.

**Comment by ethanrich** [comment]
There are already 15-16 readouts and buttons, which seems high to me.  A tab to show one comment or the other would not add further clutter. Also, the way Qt Designer allows for spacing and placing in the layouts is a nightmare.

**Comment by agricolab** [comment]
hm. my issue with tabs is they add states, and therefore increase complexity. Additionally, they hide information from the user. 

You might want to take a look in  programmatic design of the GUI. There should be a way to reserve a container and add widgets into that during runtime. This would also be useful when implementing different readouts.

**Comment by agricolab** [comment]
With Menu i meant a MenuBar à la.
[![image](https://www.tutorialspoint.com/pyqt/images/qmenubar_qmenu_qaction_widgets_output.jpg)](https://www.tutorialspoint.com/pyqt/qmenubar_qmenu_qaction_widgets.htm)

**Comment by ethanrich** [comment]
Thanks, I'm on it. Global_comment editing to a menu bar and displaying both global and trace comments in the gui.

**Comment by agricolab** [comment]
My preferred solution, as mentioned in the initial request is "Both comments should be editable and visible from the GUI, ideally in separate QTextEdits." MenuBar is an alternative, in case there are good arguments against using QTextEdits directly.

**Comment by ethanrich** [comment]
Implemented with [f9cedd1](https://github.com/translationalneurosurgery/tool-offspect/commit/f9cedd14096ec6d91aaea7737c208c43b71832a1)
