### ISSUE TITLE
Error when trying to convert TMS-EEG data from an xdf file to a cachefile

### ISSUE THREAD

**Issue by amelieziller** [translationalneurosurgery/tool-offspect#17]
When trying to convert my data from an xdf file to a cachefile with the hdf5 ending I get the following error saying string indices must be integers:
![error](https://user-images.githubusercontent.com/63000628/78147136-5ff0eb80-7433-11ea-89ac-2c01f4c83cc9.JPG)

**Comment by agricolab** [comment]
Can you try `pip install --upgrade liesl` and try again?

**Comment by amelieziller** [comment]
thanks, that worked!
