### ISSUE TITLE
Creating cache file was not possible using NMES data

### ISSUE THREAD

**Issue by don-i** [translationalneurosurgery/tool-offspect#19]
**Describe the bug**
I tried doing the visual inspection with offspect using the raw NMES data for one participant and I wanted to create the Cache-file.
Therefore, I used one .xdf file (acute NMES study) from the server.
I used the following command to do that: 
offspect tms -t test123.hdf5 -f C:\Users\Antonia\IMONAS-acute_study_120RMT-intervention_R001.xdf -pp 250 250 -c EDC_R -r SEP 
I got an error saying that it does not find the localite marker which makes sense to me because we did not use that. And that´s why offspect might not be able to find coordinates (see screenshot attached)
I read on the website (https://offline-inspect.readthedocs.io/en/latest/input/tms/notes.html) that in such case one must define the coordinates manually for each stimulus during visual inspection. But is there another possibility without using the GUI? Or is it possible to “ignore” the localite-marker?

**To Reproduce**
see command above,
I used a .xdf-file from the acute NMES study

**Expected behavior**
create a cache file which can be used for visual inspection

**Screenshots**
attached

**Desktop (please complete the following information):**
 - OS: Windows 10

![problem](https://user-images.githubusercontent.com/61696231/78356353-aa977280-75af-11ea-8781-f2d4743f4924.png)

**Comment by agricolab** [comment]
@GerJuli is working on https://github.com/translationalneurosurgery/tool-offspect/issues/13, which should address this issue, too. He is working on it in the `load_acute_tms` branch ( i guess), and you might want to give that one a try.

**Comment by GerJuli** [comment]
Yes I am currently working on this and just pushed first results. This is NOT ready to be merged in the master branch yet.

**Comment by agricolab** [comment]
Please give the newest version for cachefile creation a try, whether it solves your issue. Please note that now, the tool will not create a file if no events were found and print an abort message instead

**Comment by GerJuli** [comment]
https://github.com/translationalneurosurgery/tool-offspect/pull/25
This could solve the issue - not tested yet. Please give feedback.

**Comment by agricolab** [comment]
Can you support an example command?

**Comment by agricolab** [comment]
Closing this, because the feature is no longer a requirement per meeting from 24.04.20
