### ISSUE TITLE
Error when I use gui to access converted data

### ISSUE THREAD

**Issue by syd14** [translationalneurosurgery/tool-offspect#22]
When I enter the following functions, I receive an unbound local error.
I also tried entering `offspect gui` and choosing the file manually, but this error persists. 
Thanks in advance! 
![question](https://user-images.githubusercontent.com/62308241/78378058-bc3d4200-75d0-11ea-9fd2-6e0002df4c65.JPG)

**Comment by agricolab** [comment]
what does `offspect peek cz.hdf5`return?

**Comment by syd14** [comment]
![image](https://user-images.githubusercontent.com/62308241/78380481-358a6400-75d4-11ea-9243-b73c5df2d0e1.png)

**Comment by agricolab** [comment]
Your cachefile does not have any content, i.e. 0 traces (see also https://github.com/translationalneurosurgery/tool-offspect/issues/21). Weird thing is that you get a different error message. Maybe because you give the gui a file as an argument while in https://github.com/translationalneurosurgery/tool-offspect/issues/21 the file is selected via the gui? Could this be the case, @amelieziller?

**Comment by syd14** [comment]
I tried another data set and it also had 0 traces_count...I also tried coding without the -f in front of the cz.hdf5 like Amelie did in #21 and the same unbound local error appeared.

**Comment by agricolab** [comment]
Currently, the cachefile creation likely only works for cMEP data from mapping. @GerJuli  is currently working on an implementation for the imonas-acute data at https://github.com/translationalneurosurgery/tool-offspect/issues/13 It will be implemented soon and should fix this issue.

**Comment by agricolab** [comment]
Please give the newest version for cachefile creation a try, whether it solves your issue. Please note that now, the tool will not create a file if no events were found and print an abort message instead.

**Comment by syd14** [comment]
Hello! I just wanted to update: similar to Amelie, my `liesl xdf IMONAS-acute-study-intervention_R001.xdf -t inf ` command works well. However, the `offspect tms -f IMONAS-acute-study-intervention_R001.xdf -t IMONAS-acute-study-intervention_R001.hdf5 -pp 100 100 -c EDC_L -e "BrainVision RDA Markers" "S  2" -r cmep` ends with a RunTimeError. I added a screenshot if that helps...Does anyone have a suggestion how I could fix this error? :) Thank you!
![image](https://user-images.githubusercontent.com/62308241/79997972-6d414900-84ba-11ea-9678-56d0cb8ef4d0.png)

**Comment by agricolab** [comment]
Can this be an issue with this specific xdf-file, or does this occur with different ones, too? I am asking because the error occurs during loading the xdf-file. The same error should also occur when you use `liesl xdf IMONAS-acute-study-intervention_R001.xdf` without the `-t inf`.

**Comment by agricolab** [comment]
Using ` offspect tms -f IMONAS-acute-study-intervention_R001.xdf -t IMONAS-acute-study-intervention_R001.hdf5 -pp 100 100 -c EDC_L -e "BrainVision RDA Markers" "S 2" -r cmep`, I run tests.

First, i tested the tip of the develop branch. It run without error, but was not able to find events and therefore aborted the CacheFile creation. Second, I tested the tip of the @GerJuli s phase_dependent branch. It was able to find   1995 events, but aborted with the following exception. The traceback suggests a failure in detecting the "Stimulus comment" linked to an event.
```
Traceback (most recent call last):
  File "/home/rtgugg/anaconda3/bin/offspect", line 11, in <module>
    load_entry_point('offspect', 'console_scripts', 'offspect')()
  File "/media/rtgugg/sd/projects/tool-offspect/offspect/cli/__main__.py", line 206, in main
    cli_tms(args)
  File "/media/rtgugg/sd/projects/tool-offspect/offspect/cli/tms.py", line 165, in cli_tms
    comment_name="Stimulus comment"
  File "/media/rtgugg/sd/projects/tool-offspect/offspect/input/tms/cmep/xdfspongebob.py", line 87, in prepare_annotations
    relative="earlier",
  File "/media/rtgugg/sd/projects/tool-offspect/offspect/input/tms/cmep/xdfspongebob.py", line 82, in <listcomp>
    c
  File "/media/rtgugg/sd/projects/tool-offspect/offspect/protocols/xdf.py", line 137, in yield_comments
    idx = np.argmin(np.abs(_ct))
  File "<__array_function__ internals>", line 6, in argmin
  File "/home/rtgugg/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1267, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/rtgugg/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

**Comment by agricolab** [comment]
I think we need a bunch of testfiles to develop and debug this proper.

**Comment by agricolab** [comment]
Closing this, because the feature is no longer a requirement per meeting from 24.04.20
