### ISSUE TITLE
Feature: Setting constant onset shift for one cachefile

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#26]
**Is your feature request related to a problem? Please describe.**
Currently, it is possibly to shift the onset of MEPs in the GUI. However, for one cachefile it requires one to manually shift the onset for every single MEP.

**Describe the solution you'd like**
It would be great to have the possibility to set an onset shift and have it constant for the whole data of one Cachefile.

**Comment by agricolab** [comment]
I believe using the python API is the best approach for such batch-manipulation. I wrote a couple of examples and added them to the documentation. The one for your use-case is at https://offline-inspect.readthedocs.io/en/latest/cachefile.html#batch-manipulate and repeated here for ease of use:
```
from offspect.api import CacheFile, decode, encode
cf = CacheFile("merged.hdf5")
for ix, (data, attrs) in enumerate(cf):
    key = "onset_shift"
    old = decode(attrs[key])
    print(f"Trace {ix} {key}:", old, end=" ")
    new = old + 5
    attrs["onset_shift"] = encode(new)
    cf.set_trace_attrs(ix, attrs)
    test = decode(cf.get_trace_attrs(ix)["onset_shift"])
    print("to", test)
```
In this example, we shift all onsets by 5 samples to the right.

**Comment by agricolab** [comment]
Closing this, as we agreed a API approach is  most suitable. Find updated documentations with examples for batch manipulation https://offline-inspect.readthedocs.io/en/latest/cachefile.html
