### ISSUE TITLE
Error with offspect -tms when creating cache-file from .cnt-file

### ISSUE THREAD

**Issue by FelixQuirm** [translationalneurosurgery/tool-offspect#28]
**Describe the bug**
SmartMove protocol: When trying to create a new CacheFile from cnt-files and documentation.txt,  no module 'offspect.input.tms.contralateral_mep' is found and no cache file created.

When replacing _contralateral_mep_ with _cmep_ in the code, a different error occurs: 
The channel label does not get accepted. 

**To Reproduce**
1. Run `offspect tms -t test.hdf5 -f VvNn_VvNn_1970-01-01_00-00-01.cnt VvNn\ 1970-01-01_00-00-01.cnt documentation.txt -r contralateral_mep -c Ch1 -pp 100 100 -e 1` from command prompt in folder with said .cnt-file
2. Alternatively, run `offspect tms -t test.hdf5 -f VvNn_VvNn_1970-01-01_00-00-01.cnt VvNn\ 1970-01-01_00-00-01.cnt documentation.txt -r cmep -c Ch1 -pp 100 100 -e 1` from command prompt in folder with said .cnt-file

**Expected behavior**
A cache file is created from both .cnt-files and documentation.txt

**Desktop:**
 - OS: Windows 10

![offspect_tms_cnt_error](https://user-images.githubusercontent.com/42035995/80366621-d8f42f00-8889-11ea-888f-f4e7414eb279.png)

**Additional context**
I checked the channel labels via python &` .get_channel_info`. For the emg-cnt, the result was ['Ch1', 'Ch2', 'Ch3', .. ., 'PO8', 'Oz'], for eeg ['Fp1', 'Fpz', 'Fp2',  ... , 'PO8', 'Oz']. Replacing _Ch1_ in the code with any of these did not change the outcome.

**Comment by agricolab** [comment]
`-r contralateral_mep` is deprecated, and failing is expected behavior.

**Comment by agricolab** [comment]
I fixed the `unexpected keyword` in the most recent `develop` commit. But now i get 
```
    raise Exception(f"Received an invalid libeep file handle")
Exception: Received an invalid libeep file handle
```
This other bug is weird, because libeep as well as offspect tests pass.

**Comment by agricolab** [comment]
The invalid libeep file handle is caused by eemagines binary which i only wrapped. Weirdly enough, 
`eep-peek VvNn_VvNn_2000-12-31_23-59-59.cnt` and `eep-peek VvNn_VvNn_2000-12-31_23-59-59.cnt` run fine without exception.

**Comment by agricolab** [comment]
Yet, 
```
from libeep import peek
fname = "VvNn_VvNn_1970-01-01_00-00-01.cnt"
peek(fname)
```
fails with the exception, even though it should be behaviourally identical to the main called sucessfully by eep-peek:
```
def main():
    import sys
    filename = sys.argv[1]
    peek(filename)
```

**Comment by agricolab** [comment]
Okay, that was because i used file expansion from the terminal. Can you check whether the files `VvNn_VvNn_1970-01-01_00-00-01.cnt` and `VvNn\ 1970-01-01_00-00-01.cnt`do even exist?

**Comment by agricolab** [comment]
Similarily, `ffspect tms -t test.hdf5 -f "VvNn 2000-12-31_23-59-59.cnt" VvNn_VvNn_2000-12-31_23-59-59.cnt documentation.txt -r cmep -c Ch1 -pp 100 100 -e 1` runs without exception now, but doesnt find any traces.

Please note that i use different filenames. Adapt the snippets accordingly.

**Comment by agricolab** [comment]
@FelixQuirm  Please confirm and close if it works now.

**Comment by FelixQuirm** [comment]
Works for me now as well, thanks!
