### ISSUE TITLE
Feature: Shifting signal in GUI in y-direction

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#33]
Sometimes, the signal has an offset in y-direction. The possibility to shift that signal (optimally in the GUI) would be helpful. 
![grafik](https://user-images.githubusercontent.com/54707165/81302876-3acb4a80-907b-11ea-959c-d2d98dbad1b4.png)

**Comment by agricolab** [comment]
I am thinking about two options, both adding a line of buttons/textfields above the traceplot and below the accept/reject button.
#### Option A)
 A button called "Baseline Correction" would subtract the average of the data before the TMS onset (corrected by onset_shift) and subtract from the trace. It additionally would overwrite the data stored in the cachefile, to keep it corrected on reload.     
#### Option B)
A line identical to "onset shift", but called "vertical shift", initialized at zero and requiring manual setting.

Would you have a preference or do you think you will need both, i.e. the possibility to perform a manual y-shift in addition to baseline correction?

**Comment by BettinaTrunk** [comment]
I prefer option A: Baseline Correction. Probably, option B is then not needed.
