### ISSUE TITLE
Feature: Marking onset of MEP in GUI and calculate ptp amplitude

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#34]
Currently, no ptp amplitude of the MEP is calculated when visualising traces in the GUI. Besides that, it would be nice if the onset of the MEP would be visualised in the signal (e.g. as it is currently displayed online during a TMS-measurement with red lines) to see if there are changes needed.

**Comment by agricolab** [comment]
Related to https://github.com/translationalneurosurgery/tool-offspect/issues/18
