### ISSUE TITLE
Feature: Handling of traces where we don't have valid coordinates

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#39]
For some traces of the mapping data we don't have valid coordinates (e.g. when the camera temporarily couldn't track the coil for some reason). One example would be SaCe-pre3-ipsilesional-traces 101-104. In this case, currently the GUI raises an error and suggests to correct the xyz-coordinates. However, we have not discussed yet what to do in such cases.

I would suggest the following:

- If it's only one (or two) invalid trace, we could use the coordinates of the trace before/after depending on which trace it is: we always have 5 at the same spot, so for trace 102 for example, traces 100-105 should have similar coordinates. If the previous or following coordinates make sense would have to be decided individually.
- If more than two traces in a row don't have valid coordinates, I would reject the trial.

Would it according to this make sense and be feasible to have the three options in the GUI to either 
1: leave the coordinates at NaN and reject the trial
2: accept it and recover the coordinates from the previous trace
3: accept it and recover the coordinates from the following trace ?

What do you think?

**Comment by agricolab** [comment]
Good idea. I can put these three options as buttons into the dialogbox which opens when such a trial  is loaded. Would this be ok with you?

**Comment by agricolab** [comment]
The alternative to keep on inspecting is obviously to just manually change the coordinate entry.

**Comment by agricolab** [comment]
![image](https://user-images.githubusercontent.com/20556511/84365599-f418c500-abd1-11ea-969d-01b2a1ef0104.png)
Implemented in https://github.com/translationalneurosurgery/tool-offspect/commit/f3835e815690d4b9f8363c1ab0b0d4545033595d

**Comment by agricolab** [comment]
Closing this with https://github.com/translationalneurosurgery/tool-offspect/commit/f3835e815690d4b9f8363c1ab0b0d4545033595d, please reopen if further issues persist
