### ISSUE TITLE
Both peaks of a MEP below or above zero

### ISSUE THREAD

**Issue by don-i** [translationalneurosurgery/tool-offspect#42]
**Is your feature request related to a problem? Please describe.**
Sometimes, there is a visible MEP, but both peaks are <0 or >0, Baseline correction doesn´t help here.

**Describe the solution you'd like**
It may be helpful to move the signal up and down

**Additional context**
for example, see picture attached
![IMG_20200625_164600](https://user-images.githubusercontent.com/61696231/85828609-15101700-b789-11ea-8b59-0a1ba11ddfeb.jpg)

**Comment by agricolab** [comment]
Thanks. As far as i can see, there are two issues with this trace.
First, it has a trend, i.e. a steady decrease. Baseline correction can not remove this. Second, there is a strong 50Hz line noise, and this can affect the estimation of the peak amplitudes.

For the first, i can implement detrending, for the second i can implement a filter for line noise removal.

**Comment by agricolab** [comment]
Addressed in https://github.com/translationalneurosurgery/tool-offspect/commit/01fd281a6c1c200a67532aaa975ec22c8e4b0fe7
Please consider though. that any detrend, baseline correction, or filtering permanently alters the data in the cachefile. We currently offer no redo button! 

Additionally, consider that filtering might be repeatedly performed to achieve a  nice result and that one should first filter, than detrend, and then baseline. 
![image](https://user-images.githubusercontent.com/20556511/85866623-f4b37d00-b7c7-11ea-9c60-e684f0cd4ad5.png)

**Comment by agricolab** [comment]
Please tread with caution, when using detrending or line noise filtering, because currently, there is no `undo`. I plan to implement this in some fashion, though (see https://github.com/translationalneurosurgery/tool-offspect/issues/44).
