### ISSUE TITLE
Feature: Coordinate offset/scaling-correction for MEP mapping

### ISSUE THREAD

**Issue by FelixQuirm** [translationalneurosurgery/tool-offspect#43]
**Is your feature request related to a problem? Please describe.**
The coordinates obtained for stimulation positions when recording with the SmartMove TMS system result in a considerable translational offset and scaling error when plotted on our standard brain map (see below).

![BuUl_2019-06-18_EDC_P](https://user-images.githubusercontent.com/42035995/85850698-9aa5be00-b7ad-11ea-91d7-b6f6b3a70675.png)

**Describe the solution you'd like**
For the two stimulation points (C3 & C4 in the 10-20 system) corresponding to M1, the 'accurate' positions on the brain map are known (see https://github.com/translationalneurosurgery/stroke-tms-maps/blob/master/intens_tms/proc/plot.py#L34). As the coordinate values are internally coherent, it should be sufficient to calculate a translational correction and scaling factor based on these two points and apply it to all coordinates accordingly.
It would be advantageous if both the scaling factor and the offset could be automatically calculated when generating the cache file and be manually adjustable. The original coordinates should remain unchanged or at least be stored. 

**Alternative solutions**
For the time being, I will calculate the scaling factor and offset as described above and adjust the xyz-Values of each event directly. This will allow me to create maps with the current plotting function. The original coordinates are not kept in these adjusted files, so I'll store a backup pf all original files.

**Additional context**
While indispensable for the current set of SmartMove EMG data, this feature would also be very helpful in all other cases where a smaler offset or scaling error in stimulation coordinates may exist.

**Comment by agricolab** [comment]
One can estimate the scaling from the distance between the two hotspots, as ideally, it should be identical to the distance between the two M1s. Considering that scaling seems to be mainly an issue with the roboTMS coordinates (see https://github.com/translationalneurosurgery/tool-offspect/issues/1), and there the scaling seems to be constant, we can probably skip scaling for now.

Feel free to reopen, if we need offset correction for the localite datasets.

Anyways, see [correct_coords.py](https://github.com/translationalneurosurgery/tool-offspect/blob/develop/offspect/examples/correct_coords.py) for a first draft for a solution.
