### ISSUE TITLE
Feature: Log/Undo baseline correction, detrending and line noise removal

### ISSUE THREAD

**Issue by agricolab** [translationalneurosurgery/tool-offspect#44]
**Is your feature request related to a problem? Please describe.**
When an examiner performs baseline correction, detrending or line-noise filtering, every change is immediately affecting the TraceData stored in the CacheFile and can not be undone. Additionally, there is no logging of when or who performed any changes. Currently, for line noise removal,  there is rudimentary logging in the comments field.

**Describe the solution you'd like**
I want to add a field, where each manipulation is logged, instead of adding this to the `comments` field. Additionally, i could keep a copy of the data in a transient cache, which is updated every time a new trace is loaded into memory, e.g. via `next`, `previous`, or via arbitrary trace selection. Whenever the examiner manipulates the data, the data stored in the CacheFile is being manipulated (as it is right now), but this transient copy of the original stays unaffected. The (to-be-implemented) undo-button would overwrite the data again with this transient copy of the original. When the examiner switches to a different trace, this `undo`-cache is being cleared, making all changes permanent. This means that as long as the examiner works on this trace, they can undo to the state of the data when loaded, but when a new trace is selected, changes become permanent.

**Describe alternatives you've considered**
Every change is memorized as a step, and logged (e.g. in the `preprocessing` field) but the original data is never affected. Instead, whenever a new trace is loaded, each manipulation is performed again on the fly. The disadvantage is an increased load time, especially when many preprocessing steps have been performed, but the huge advantage is that the raw data will never be overwritten. An alternative is that we store a two-dimensional Trace in the CacheFile, with the first the one to be plotted, and the second the raw. This would reduce load time, but is a breaking change to all of our current CacheFiles. 

**Additional context**
See https://github.com/translationalneurosurgery/tool-offspect/issues/42

**Comment by agricolab** [comment]
Maybe @BettinaTrunk and @don-i want to add their opinions?

**Comment by BettinaTrunk** [comment]
I also think that the possibility of undoing and logging all actions would be very beneficial. The solution you describe in the field 'Describe the solution you'd like' sounds sensible to me as re-doing changes would probably mostly be necessary while working on one trace. In case the examiner realises that there are (many) changes which were not correct, a new Cachefile can always be re-created from the raw data.

**Comment by agricolab** [comment]
I implemented it  now in the following fashion:

All preprocessing steps are primarly cached, and a log of the steps is saved in a hidden field in the CacheFile. This means that, e.g. when you switch between Traces, or when you load the CacheFile again after a break, those cached steps are only replayed, but do not affect at all the data stored in the CacheFile. The advantage is that they can be undone one by one at any time. 
If too many steps are cached, and you feel a drop in speed, or you are comfortable with the preprocessing, you can apply them, either from the menu or with `ctrl-a`. The steps are applied permanently, can not be undone anymore, and the TraceData in the CacheFile is being overwritten.

![output](https://user-images.githubusercontent.com/20556511/86001466-371acb00-ba0f-11ea-81f7-812406d360ff.gif)

Resolved with https://github.com/translationalneurosurgery/tool-offspect/commit/91390a6f4e1bc8b817afb6f3f97ae7cc63289ede

**Comment by agricolab** [comment]
Resolved with https://github.com/translationalneurosurgery/tool-offspect/commit/91390a6f4e1bc8b817afb6f3f97ae7cc63289ede
