### ISSUE TITLE
Unable to launch offspect from command line

### ISSUE THREAD

**Issue by ethanrich** [translationalneurosurgery/tool-offspect#5]
After pip installation of course
![SharedScreenshot](https://user-images.githubusercontent.com/48725637/77047453-0addc000-69c5-11ea-92f7-7fdb186eaf8c.jpg)

**Comment by agricolab** [comment]
It seems the offspect package is not installed in your Python. Did you execute `pip install -e .` to install the package?

**Comment by ethanrich** [comment]
No errors during installtion.

`offspect` is listed in `pip freeze`

It seems that creating a virtual environment in WinPython needs some tweaking.

**Comment by agricolab** [comment]
You mentioned, that for some reason, Anaconda Python did not work on your machine? Maybe your PATH is messed up from this installation.  You might consider to check and tweak your user-specific PATHs to make sure it finds the proper python https://www.computerhope.com/issues/ch000549.htm 

You might also want to try Pythonxy as alternative: https://python-xy.github.io/ , create a new User, or there is also the option to run Linux as a subsystem on Windows https://docs.microsoft.com/de-de/windows/wsl/install-win10

**Comment by ethanrich** [comment]
Successfully installed anaconda. Now, the GUI is not found during importing. 

After accessing python from the Anaconda Prompt, various packages were shown to not be installed. For example, I was told that `ModuleNotFoundError: No module named 'PyQt5.sip'`

The following commands in Anaconda Prompt solved these issues:

`pip install --user -I PyQt5`

Possibly:
`setx path "%path%;<path given in warning message>` 

`pip install nibabel`

`pip install nilearn`

**Comment by agricolab** [comment]
Thanks, right - we use nibabel and nilearn with the GUI, but they are not in requirements.txt.

**Comment by agricolab** [comment]
Related to the unfindable dll: https://stackoverflow.com/questions/42497689/importerror-pyqt5-anaconda Seems like anaconda and pyqt5 have some issues on windows.
