### ISSUE TITLE
Exception thrown during GUI initialization

### ISSUE THREAD

**Issue by ethanrich** [translationalneurosurgery/tool-offspect#6]
`Exception 'FigureCanvasQTAgg' object has no attribute 'axes'`

Results in the GUI lacking the glass brain plot

**Comment by agricolab** [comment]
Is this still with WinPython or Anaconda?

**Comment by agricolab** [comment]
This is probably related to the nonstandard designer which was used for creation of the other `.ui`. Can you check whether `offspect gui -r XS` works on your machine?

**Comment by agricolab** [comment]
I demoted and (re)promoted the QWidgets in Designer and recompiled the pys from the uis, and tested it manually. Give it a try.

**Comment by ethanrich** [comment]
The following commands work after this fix:

`offspect gui`
`offspect gui -r HR`
`offspect gui -r LR`
`offspect gui -r XS`

Thanks very much.
