### ISSUE TITLE
Random access selection of traces

### ISSUE THREAD

**Issue by agricolab** [translationalneurosurgery/tool-offspect#9]
Currently, we have to click prev and next repetitively, direct access via typing a number into a field or selection from a menu could be an option.

**Comment by ethanrich** [comment]
I'm on it. Will program into gui branch first

**Comment by agricolab** [comment]
Implemented with https://github.com/translationalneurosurgery/tool-offspect/commit/7383ddbf786f987738e578cac741b0b84e4457fb
